[package]
name = "lite-rpc"
version = "0.1.0"
edition = "2021"
description = "A lite version of solana rpc to send and confirm transactions"

[workspace]
members = [
    "bench-utils"
]

[[bench]]
name="tps"
harness=false

[dev-dependencies]
bench-utils = { path = "./bench-utils" }
csv = "1.1.6"

[dependencies]
solana-client = "1.14.11"
solana-sdk = "1.14.11"
solana-transaction-status = "1.14.11"
solana-version = "1.14.11"
actix-web = "4.2.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.24.1", features = ["full"]} 
bincode = "1.3.3"
bs58 = "0.4.0"
base64 = "0.21.0"
thiserror = "1.0.38"
futures = "0.3.25"
bytes = "1.3.0"
reqwest = "0.11.13"
anyhow = "1.0.68"
log = "0.4.17"
simplelog = "0.12.0"
clap = { version = "4.0.32", features = ["derive"] }
dashmap = "5.4.0"
const_env = "0.1.2"
jsonrpsee = { version = "0.16.2", features = ["macros", "full"] }
