[package]
name = "lite-rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-client = { git = "https://github.com/solana-labs/solana.git" }
solana-sdk = { git = "https://github.com/solana-labs/solana.git" } 
solana-clap-utils = { git = "https://github.com/solana-labs/solana.git" } 
solana-cli-config = { git = "https://github.com/solana-labs/solana.git" } 
solana-pubsub-client = { git = "https://github.com/solana-labs/solana.git" } 
solana-account-decoder = { git = "https://github.com/solana-labs/solana.git" } 
solana-entry = { git = "https://github.com/solana-labs/solana.git" } 
solana-faucet = { git = "https://github.com/solana-labs/solana.git" } 
solana-gossip = { git = "https://github.com/solana-labs/solana.git" } 
solana-ledger = { git = "https://github.com/solana-labs/solana.git" } 
solana-measure = { git = "https://github.com/solana-labs/solana.git" } 
solana-metrics = { git = "https://github.com/solana-labs/solana.git" } 
solana-perf = { git = "https://github.com/solana-labs/solana.git" } 
solana-poh = { git = "https://github.com/solana-labs/solana.git" } 
solana-rayon-threadlimit = { git = "https://github.com/solana-labs/solana.git" } 
solana-rpc-client-api = { git = "https://github.com/solana-labs/solana.git" } 
solana-runtime = { git = "https://github.com/solana-labs/solana.git" } 
solana-send-transaction-service = { git = "https://github.com/solana-labs/solana.git" } 
solana-stake-program = { git = "https://github.com/solana-labs/solana.git" } 
solana-storage-bigtable = { git = "https://github.com/solana-labs/solana.git" } 
solana-streamer = { git = "https://github.com/solana-labs/solana.git" } 
solana-tpu-client = { git = "https://github.com/solana-labs/solana.git" } 
solana-transaction-status = { git = "https://github.com/solana-labs/solana.git" } 
solana-version = { git = "https://github.com/solana-labs/solana.git" } 
solana-vote-program = { git = "https://github.com/solana-labs/solana.git" } 
solana-rpc = { git = "https://github.com/solana-labs/solana.git" } 

tokio = { version = "1.14.1", features = ["full"]}
futures = "0.3.25"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0" }
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
jsonrpc-pubsub = "18.0.0"
clap = { version = "4.0.29", features = ["derive"] }

base64 = "0.13.0"
bincode = "1.3.3"
bs58 = "0.4.0"
crossbeam-channel = "0.5"
dashmap = "4.0.2"
itertools = "0.10.5"
libc = "0.2.131"
log = "0.4.17"
rayon = "1.5.3"
regex = "1.6.0"
serde = "1.0.144"
serde_derive = "1.0.103"
serde_json = "1.0.83"
soketto = "0.7"
spl-token = { version = "=3.5.0", features = ["no-entrypoint"] }
spl-token-2022 = { version = "=0.4.3", features = ["no-entrypoint"] }
stream-cancel = "0.8.1"
thiserror = "1.0"
tokio-util = { version = "0.6", features = ["codec", "compat"] }

[dev-dependencies]
csv = "1.1.6"
serde = { version = "1", features = ["derive"]}

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
