[package]
name = "lite-rpc"
version = "0.1.0"
edition = "2021"
description = "A lite version of solana rpc to send and confirm transactions"

[workspace]
members = [
    "lite-client",
    "bench-utils"
]

[[bench]]
name="tps"
harness=false

[dev-dependencies]
lite-client = { path = "./lite-client" }
bench-utils = { path = "./bench-utils" }
csv = "1.1.6"

[dependencies]
solana-client = { git = "https://github.com/solana-labs/solana.git" }
solana-sdk = { git = "https://github.com/solana-labs/solana.git" } 
solana-version = { git = "https://github.com/solana-labs/solana.git" } 
solana-transaction-status = { git = "https://github.com/solana-labs/solana.git" } 
actix-web = "4.2.1"
serde = { version = "1.0.150", features = ["derive"] }
serde_json = "1.0.89"
tokio = { version = "1.23.0", features = ["full"]} 
bincode = "1.3.3"
bs58 = "0.4.0"
base64 = "0.20.0"
thiserror = "1.0.37"
futures = "0.3.25"
bytes = "1.3.0"
reqwest = "0.11.13"
anyhow = "1.0.66"
log = "0.4.17"
simplelog = "0.12.0"
clap = { version = "4.0.29", features = ["derive"] }
