[package]
name = "lite-rpc"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "lite-client",
    "lite-bench-utils"
]

[[bench]]
name="tps"
harness=false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dev-dependencies]
csv = "1.1.6"
serde = { version = "1", features = ["derive"]}
lite-client = { path ="./lite-client" }
lite-bench-utils = { path = "./lite-bench-utils" }
log = "0.4.17"
simplelog = "0.12.0"

[dependencies]
solana-client = { git = "https://github.com/solana-labs/solana.git" }
solana-sdk = { git = "https://github.com/solana-labs/solana.git" } 
solana-clap-utils = { git = "https://github.com/solana-labs/solana.git" } 
solana-cli-config = { git = "https://github.com/solana-labs/solana.git" } 
solana-pubsub-client = { git = "https://github.com/solana-labs/solana.git" } 
solana-account-decoder = { git = "https://github.com/solana-labs/solana.git" } 
solana-entry = { git = "https://github.com/solana-labs/solana.git" } 
solana-faucet = { git = "https://github.com/solana-labs/solana.git" } 
solana-gossip = { git = "https://github.com/solana-labs/solana.git" } 
solana-ledger = { git = "https://github.com/solana-labs/solana.git" } 
solana-measure = { git = "https://github.com/solana-labs/solana.git" } 
solana-metrics = { git = "https://github.com/solana-labs/solana.git" } 
solana-perf = { git = "https://github.com/solana-labs/solana.git" } 
solana-poh = { git = "https://github.com/solana-labs/solana.git" } 
solana-rayon-threadlimit = { git = "https://github.com/solana-labs/solana.git" } 
solana-rpc-client-api = { git = "https://github.com/solana-labs/solana.git" } 
solana-runtime = { git = "https://github.com/solana-labs/solana.git" } 
solana-send-transaction-service = { git = "https://github.com/solana-labs/solana.git" } 
solana-stake-program = { git = "https://github.com/solana-labs/solana.git" } 
solana-storage-bigtable = { git = "https://github.com/solana-labs/solana.git" } 
solana-streamer = { git = "https://github.com/solana-labs/solana.git" } 
solana-tpu-client = { git = "https://github.com/solana-labs/solana.git" } 
solana-transaction-status = { git = "https://github.com/solana-labs/solana.git" } 
solana-version = { git = "https://github.com/solana-labs/solana.git" } 
solana-vote-program = { git = "https://github.com/solana-labs/solana.git" } 
solana-rpc = { git = "https://github.com/solana-labs/solana.git" } 

tokio = { version = "1.14.1", features = ["full"]}
tokio-util = { version = "0.6", features = ["codec", "compat"] }
futures = "0.3.25"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0" }
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
jsonrpc-pubsub = "18.0.0"
clap = { version = "4.0.29", features = ["derive"] }
procinfo = "0.4.2"

base64 = "0.13.1"
bincode = "1.3.3"
bs58 = "0.4.0"
crossbeam-channel = "0.5.6"
dashmap = "5.4.0"
itertools = "0.10.5"
libc = "0.2.138"
log = "0.4.17"
rayon = "1.6.1"
regex = "1.7.0"
serde = "1.0.149"
serde_derive = "1.0.149"
serde_json = "1.0.89"
soketto = "0.7.1"
spl-token = { version = "=3.5.0", features = ["no-entrypoint"] }
spl-token-2022 = { version = "0.5.0", features = ["no-entrypoint"] }
stream-cancel = "0.8.1"
thiserror = "1.0.37"
